#!/bin/bash

run () {
   docker network create anhdiepmmk
   docker stop mongodb1 || true
   docker run --network anhdiepmmk --name mongodb1 --rm -itd -p 27017:27017 mongo:4.4.4
   docker stop frontend-react-app || true
   docker run --network anhdiepmmk -itd --rm --name frontend-react-app -p 3001:80 anhdiepmmk/frontend-react-app:latest
   docker stop backend-node-app || true
   docker run --network anhdiepmmk -itd --rm --name backend-node-app -p 3002:3000 anhdiepmmk/backend-node-app:latest
   docker ps
}

start () {
  docker start mongodb1 || true
  docker start frontend-react-app || true
  docker start backend-node-app || true
}

stop () {
  docker stop mongodb1 || true
  docker stop frontend-react-app || true
  docker stop backend-node-app || true
}

build () {
  cd ./backend
  docker build -t anhdiepmmk/backend-node-app:latest .
  cd ../frontend
  docker build -t anhdiepmmk/frontend-react-app:latest .
  cd ../
}

push () {
  USERNAME=$(docker system info | grep Usernamee)
  if [ ! -z "$USERNAME" ]
  then
   docker push anhdiepmmk/backend-node-app
   docker push anhdiepmmk/frontend-react-app:latest
  else
    echo "Oops! It's seem you are not login to hub.docker.io. Let use run docker login --help to see instruction"
  fi
}

logs () {
  docker logs $1 -f
}

help () {
  echo "
    Usage:  ./cli COMMAND

    Manage networks

    Commands:
      run                  Run all needed container
      start                Start all needed container
      stop                 Stop all needed container
      logs CONTAINER_NAME  Display logs
      build                Build image from Dockerfile
      push                 Publish image to registry

    Run './cli --help' for more information on a command.
  "
}

case $1 in
  "run")
    run
    exit
    ;;
  "start")
    start
    exit
    ;;
  "stop")
    stop
    exit
    ;;
  "logs")
    logs $2
    exit
    ;;
  "build")
    build
    exit
    ;;
  "push")
    push
    exit
    ;;
  *)
    help
    exit
    ;;
esac