#!/bin/bash

help () {
  echo "
    Usage:  ./cli-compose COMMAND

    Manage networks

    Commands:
      up                   Create and start containers
      down                 Stop and remove containers, networks, images, and volumes
      logs                 View output from containers
      build                Build or rebuild services

    Run './cli-compose --help' for more information on a command.
  "
}

up () {
  docker-compose up $1
}

down () {
  docker-compose down $1
}

logs () {
  docker-compose logs $1
}

build () {
  docker-compose build $1
}

case $1 in
  "up")
    up $2
    exit
    ;;
  "down")
    down $2
    exit
    ;;
  "logs")
    logs $2
    exit
    ;;
  "build")
    build $2
    exit
    ;;
  *)
    help
    exit
    ;;
esac